# Dosya Adı: Dockerfile.worker

FROM python:3.10-slim
WORKDIR /app

# Gerekli Python kütüphanelerini kopyala ve yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Uygulama kodunu kopyala
COPY . /app
